name: Polaris SCA (Daily)
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  polaris-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: ${{ github.repository_owner }}
          polaris_project_name: ${{ github.event.repository.name }}
          polaris_assessment_types: 'SCA'
          github_token: ${{ secrets.GITHUB_TOKEN }}
